In [2]:
import torch

x = torch.tensor(2.0, requires_grad=True)

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

y = sigmoid(x)
print(y)

y.backward()

x.grad

tensor(0.8808, grad_fn=<MulBackward0>)


tensor(0.1050)

In [5]:
import math

val = 1 / (1 + math.exp(-2))

grad = val * (1-val)
print(grad)

0.10499358540350662


In [28]:
import torch

x = torch.tensor([2.0], requires_grad=True)

y = x**2
z = 3 * y + 1

z.backward()
print(x.grad)

y.grad_fn

tensor([12.])


In [30]:
def print_comp_grah(tensor, indent=0):
    print(' ' * indent + str(tensor))
    if hasattr(tensor, 'grad_fn') and tensor.grad_fn is not None:
        print(' ' * (indent + 2) + str(tensor.grad_fn))
        for funcs in tensor.grad_fn.next_functions:
            if funcs is None: continue
            print_comp_grah(funcs, indent + 4)

x = torch.tensor([2.0], requires_grad=True)

y = x**2
z = 3 * y + 1
z.backward()
print_comp_grah(z)

tensor([13.], grad_fn=<AddBackward0>)
    (<MulBackward0 object at 0x7fa275a00460>, 0)
    (None, 0)


In [44]:
import torch

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

def simple_fun(x):
    return x ** 2

# y = simple_fun(x).sum()
# y.backward()
# print(x.grad)

with torch.no_grad():
    y = simple_fun(x).sum()
    print(y.requires_grad)

for i in range(5):
    y = simple_fun(x).sum()
    print(y.requires_grad)
    y.backward()

    
print(x.grad)


False
True
True
True
True
True
tensor([10., 20., 30.])
