In [2]:
import scipy.linalg

# 定义矩阵A
A = [[2, 4, 2],
     [4, 9, 3],
     [-2, 3, 4]]

# 进行LU分解
P, L, U = scipy.linalg.lu(A)

# 打印结果
print("P矩阵:")
print(P)
print("L矩阵:")
print(L)
print("U矩阵:")
print(U)


P矩阵:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L矩阵:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.06666667  1.        ]]
U矩阵:
[[4.         9.         3.        ]
 [0.         7.5        5.5       ]
 [0.         0.         0.86666667]]


In [8]:

A = np.array([
    [2,4,2],
    [4,9,3],
    [-2,3,4],
])

x = [2,2,4]

A @ x

array([20, 38, 18])

In [11]:
y = np.array([20, -2, 52])
x = np.array([2,2,4])

L = np.array([
    [1,0,0],
    [2,1,0],
    [-1,7,1]
])

U = np.array([
    [2,4,2],
    [0,1,-1],
    [0,0,13],
])



U @ x

array([20, -2, 52])

In [6]:
import numpy as np

# 定义矩阵A和向量b
A = np.array([[1, 6],
              [2, -1],
              [3, 1],
              [5, -3],
              [6, 1],
              [7, -2]])

b = np.array([1, 9, 5, 3, 4, 1])

# 使用NumPy的linalg.qr函数进行QR分解
Q, R = np.linalg.qr(A)
print(Q)
print(R)

# 计算QTb
Q_T_b = Q.T @ b

# 求解上三角系统RTRx = RTQTb
# 由于R是上三角矩阵，RT也是上三角矩阵，因此RTR仍然是上三角矩阵
# 可以使用NumPy的linalg.solve函数直接求解
x = np.linalg.solve(R.T @ R, R.T @ Q_T_b)

# 打印结果
print("最小二乘解x：")
print(x)

print(b - A @ x)

[[-0.08980265  0.86733581]
 [-0.1796053  -0.10499328]
 [-0.26940795  0.19629179]
 [-0.44901326 -0.33323955]
 [-0.53881591  0.25107089]
 [-0.62861856 -0.15520746]]
[[-11.13552873   1.43684242]
 [  0.           7.06650436]]
最小二乘解x：
[0.65891473 0.10658915]
[-0.29844961  7.78875969  2.91666667  0.0251938  -0.06007752 -3.39922481]


In [28]:
import numpy as np

A = np.array([
    [0.6, 10],
	[0.29, 15],
	[0.7, 7],
	[0.55, 6],
	[0.59, 7],
	[0.67, 6],
	[0.4, 10],
	[0.89, 6],
])

print(np.linalg.matrix_rank(A))

b = np.array([6,8,3,5,5,5,7,5])

ATA = A.T @ A
ATb = A.T @ b
L = np.linalg.cholesky(ATA)
print(ATA.shape)
print(ATb.shape)
y = np.linalg.solve(L, ATb)

x = np.linalg.solve(L.T, y)
print(x)





2
(2, 2)
(2,)
[1.83573576 0.52272596]


In [31]:
import numpy as np

A = np.array([
    [0.6, 10],
	[0.29, 15],
	[0.7, 7],
	[0.55, 6],
	[0.59, 7],
	[0.67, 6],
	[0.4, 10],
	[0.89, 6],
])

b = np.array([6,8,3,5,5,5,7,5])

Q, R = np.linalg.qr(A)
c = Q.T @ b

x = np.linalg.solve(R, c)

print(c)
print(R @ x)


[-14.07474342  -7.31752506]
[-14.07474342  -7.31752506]
