# 常用操作

In [ ]:
!pip3 install numpy

In [2]:
import numpy as np

print('\n创建数组')
print(np.array([1,2,3,4,5], dtype=np.float32))
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.arange(1, 10).reshape(3, 3))
print(np.linspace(0, 1, 5))
print(np.random.rand(2, 3))
print(np.random.randn(2, 3))

# 索引
print('\n索引')
a = np.arange(1, 11).reshape(2, -1)
print(f'a:\n{a}')
print(f'a[0, -1]: {a[0, -1]}')
print(f'a[0]: {a[0]}')


# 切片
print('\n切片')
b = np.arange(1, 11)
print(f'\nb[1:9]: \n{b[1:9]}')
print(f'b[1:9:2]: \n{b[1:9:2]}')
print(f'b[1:-1]: \n{b[1:-1]}')
print(f'b[2::2]: \n{b[2::2]}')
print(f'b[9:1:-1]: \n{b[9:1:-1]}')

print(f'a[:, 2:5]: \n{a[:, 2:5]}')

# 复制和视图
print('\n复制和视图')
c = b[1:9]
d = b[1:9].copy()
c[0] = 100
print(f'b: {b}')
print(f'c: {c}, c.base: {c.base}')
print(f'd: {d}, d.base: {d.base}')

# 布尔数组索引
print('\n布尔数组索引')
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
print(x.sum(-1))
mask = (x.sum(-1) % 2) == 0
print(mask)
print(x[mask])


创建数组
[1. 2. 3. 4. 5.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0.   0.25 0.5  0.75 1.  ]
[[0.08876537 0.99938286 0.50661212]
 [0.96659569 0.15800339 0.5375998 ]]
[[ 1.20128572  1.60002802 -0.82280903]
 [-0.84326842  1.06571187  2.0166032 ]]

索引
a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a[0, -1]: 5
a[0]: [1 2 3 4 5]

切片

b[1:9]: 
[2 3 4 5 6 7 8 9]
b[1:9:2]: 
[2 4 6 8]
b[1:-1]: 
[2 3 4 5 6 7 8 9]
b[2::2]: 
[3 5 7 9]
b[9:1:-1]: 
[10  9  8  7  6  5  4  3]
a[:, 2:5]: 
[[ 3  4  5]
 [ 8  9 10]]

复制和视图
b: [  1 100   3   4   5   6   7   8   9  10]
c: [100   3   4   5   6   7   8   9], c.base: [  1 100   3   4   5   6   7   8   9  10]
d: [2 3 4 5 6 7 8 9], d.base: None

布尔数组索引
[ 3 12 21 30]
[False  True False  True]
[[ 3  4  5]
 [ 9 10 11]]


In [2]:
import numpy as np 
b = np.arange(1, 11)
mask = (b % 2) == 0
print(type(mask))
print(b[mask].base)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
None


In [24]:
# 维度和形状
arr1 = np.array([[1,2,3], [4,5,6]], ndmin=3)
print('array shape:', arr1.shape)
print(arr1[0])

arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)
print(arr2.base)

array shape: (1, 2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [26]:
# 遍历数组

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

for idx, x in np.ndenumerate(arr):
    print(idx, x)

1
2
3
4
5
6
7
8
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


# 连接数组

## concatenate

In [32]:
arr1 = np.arange(1, 5).reshape(2, 2)
arr2 = np.arange(6, 10).reshape(2, 2)
arr = np.concatenate((arr1, arr2), axis=0)
print(arr1)
print(arr2)

print(arr)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]


## stack

In [6]:
a = np.arange(1, 7).reshape((2, 3))
b = np.arange(7, 13).reshape((2, 3))
c = np.arange(13, 19).reshape((2, 3))
d = np.arange(19, 25).reshape((2, 3))

t = np.stack([a, b, c, d], axis=0)
print(f'axis=0, shape: {t.shape}: \n{t}')

t = np.stack([a, b, c, d], axis=1)
print(f'\naxis=1, shape: {t.shape}: \n{t}')

t = np.stack([a, b, c, d], axis=2)
print(f'\naxis=2, shape: {t.shape}: \n{t}')
print(t[0][0])

axis=0, shape: (4, 2, 3): 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]

axis=1, shape: (2, 4, 3): 
[[[ 1  2  3]
  [ 7  8  9]
  [13 14 15]
  [19 20 21]]

 [[ 4  5  6]
  [10 11 12]
  [16 17 18]
  [22 23 24]]]

axis=2, shape: (2, 3, 4): 
[[[ 1  7 13 19]
  [ 2  8 14 20]
  [ 3  9 15 21]]

 [[ 4 10 16 22]
  [ 5 11 17 23]
  [ 6 12 18 24]]]
[ 1  7 13 19]


## hstack, vstack, dstack

In [10]:
arr1 = np.arange(1,9).reshape(2,4)
arr2 = np.arange(10,16).reshape(2,3)

print(f'arr1:\n{arr1}')
print(f'arr2:\n{arr2}')

arr = np.hstack((arr1, arr2))
print(f'hstack: \n{arr}')


arr2 = np.arange(10,18).reshape(2,4)

arr = np.vstack((arr1, arr2))
print(f'\nvstack: \n{arr}')

arr = np.dstack((arr1, arr2))
print(f'\ndstack: \n{arr}')
print(arr.shape)

arr1:
[[1 2 3 4]
 [5 6 7 8]]
arr2:
[[10 11 12]
 [13 14 15]]
hstack: 
[[ 1  2  3  4 10 11 12]
 [ 5  6  7  8 13 14 15]]

vstack: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]
 [14 15 16 17]]

dstack: 
[[[ 1 10]
  [ 2 11]
  [ 3 12]
  [ 4 13]]

 [[ 5 14]
  [ 6 15]
  [ 7 16]
  [ 8 17]]]
(2, 4, 2)


# 广播

In [11]:
import numpy as np

a = np.arange(1,6).reshape(5,1)
b = np.arange(1,7).reshape(1, -1)
c = np.arange(1,7)
d = np.array(2)

print(f'a {a.shape}, {a}')
print(f'b {b.shape}, {b}')
print(f'c {c.shape}, {c}')
print(f'd {d.shape}, {d}')


print(f'\na * b: \n{a * b}')
print(f'\na * c: \n{a * c}')
print(f'\nb + c: \n{b + c}')
print(f'\na * d: \n{a * d}')

a (5, 1), [[1]
 [2]
 [3]
 [4]
 [5]]
b (1, 6), [[1 2 3 4 5 6]]
c (6,), [1 2 3 4 5 6]
d (), 2

a * b: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]]

a * c: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]]

b + c: 
[[ 2  4  6  8 10 12]]

a * d: 
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


# 算数运算

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)
print(a**b)
print(np.sin(a) + 3)
print(np.log(a))



[ 4 10 18]
[  1  32 729]
[3.84147098 3.90929743 3.14112001]
[0.         0.30103    0.47712125]


# 矩阵相关

In [21]:
print(np.diag([1,2,3]))

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([
    [1,2,3],
    [0,1,4],
    [5,6,0],
])

print(a.dot(b))
print(a @ c)

print(a.T)
print(np.linalg.det(c))
print(np.linalg.inv(c))
print(np.round(np.linalg.pinv(np.arange(1, 10).reshape(3, 3)), 4))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
32
[16 22 11]
[1 2 3]
0.9999999999999964
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
[[-0.6389 -0.1667  0.3056]
 [-0.0556  0.      0.0556]
 [ 0.5278  0.1667 -0.1944]]


# 添加维度

In [25]:
x = np.array([[1,2], [3,4], [5,6]])
print('axis=0', np.expand_dims(x, axis=0).shape, '\n', np.expand_dims(x, axis=0))
print('axis=1', np.expand_dims(x, axis=1).shape, '\n', np.expand_dims(x, axis=1))
print('axis=2', np.expand_dims(x, axis=2).shape, '\n', np.expand_dims(x, axis=2))

print('axis=0', x[None, :, :])
print('axis=1', x[:, np.newaxis, :])
print('axis=2', x[:, :, None])


axis=0 (1, 3, 2) 
 [[[1 2]
  [3 4]
  [5 6]]]
axis=1 (3, 1, 2) 
 [[[1 2]]

 [[3 4]]

 [[5 6]]]
axis=2 (3, 2, 1) 
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
axis=0 [[[1 2]
  [3 4]
  [5 6]]]
axis=1 [[[1 2]]

 [[3 4]]

 [[5 6]]]
axis=2 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


# 删除维度

In [31]:
x = np.arange(1, 25).reshape(3,4,2)
print(x)

print(x[:,:,0])
print(x[...,0])
print(x.mean(axis=2))

x = np.arange(1, 6).reshape(5,1)
print(f'x: {x}')
print(f'x.squeeze: {x.squeeze()}')

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 1.5  3.5  5.5  7.5]
 [ 9.5 11.5 13.5 15.5]
 [17.5 19.5 21.5 23.5]]
x: [[1]
 [2]
 [3]
 [4]
 [5]]
x.squeeze: [1 2 3 4 5]
